Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [2]:
b = np.zeros((3, 3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3 творіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [3]:
rng = np.random.default_rng()
c = rng.integers(low=1, high=11, size=(5, 5))
print(c)

[[ 2  4  1  9  4]
 [ 2  3  2  2  5]
 [ 2 10  7  3  8]
 [ 9  2  6  2  1]
 [ 2 10  3  7  4]]


4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [4]:
rng = np.random.default_rng()
d = rng.random(size=(4, 4))
print(d)

[[0.52528999 0.81877877 0.71378291 0.65621218]
 [0.03441809 0.68447736 0.03155857 0.87599974]
 [0.25179722 0.38150994 0.41010587 0.69875801]
 [0.89649894 0.79246204 0.09338547 0.07822789]]


5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [5]:
rng = np.random.default_rng()
e = rng.integers(11, size=(5))
f = rng.integers(11, size=(5))
print(e)
print(f)
sum = e + f
print(f'сумма {sum}')
dif = e - f
print(f'різниця {dif}')
mul = e * f
print(f'перемноження елементів {mul}')

[1 6 4 3 4]
[7 8 8 3 3]
сумма [ 8 14 12  6  7]
різниця [-6 -2 -4  0  1]
перемноження елементів [ 7 48 32  9 12]


6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [6]:
rng = np.random.default_rng()
g = rng.integers(5, size=(7))
h = rng.integers(5, size=(7))
print(f'g {g}')
print(f'h {h}')
gh = np.dot(g, h)
print(f'скалярний добуток {gh}')

g [1 4 0 1 0 0 4]
h [1 0 1 0 2 1 0]
скалярний добуток 1


7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [7]:
rng = np.random.default_rng()
i = rng.integers(low=1, high=11, size=(2, 2))
j = rng.integers(low=1, high=11, size=(2, 3))
print(i)
print(j)
ij = np.dot(i, j)
print(f'перемножені матриці {ij}')

[[9 3]
 [1 4]]
[[ 1  5  5]
 [10  6  5]]
перемножені матриці [[39 63 60]
 [41 29 25]]


8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [8]:
rng = np.random.default_rng()
k = rng.integers(low=1, high=11, size=(3, 3))
print(f'звичайна {k}')
print(f' обернена {np.linalg.inv(k)}')

звичайна [[ 9  9  3]
 [ 6 10 10]
 [ 1  5  4]]
 обернена [[ 0.06410256  0.13461538 -0.38461538]
 [ 0.08974359 -0.21153846  0.46153846]
 [-0.12820513  0.23076923 -0.23076923]]


9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [9]:
rng = np.random.default_rng()
l = rng.random(size=(4, 4))
lt = l.T
print(f'звичайна {l}')
print(f'транспонована {lt}')

звичайна [[0.29619515 0.55347917 0.21943692 0.73050168]
 [0.9800448  0.29694267 0.7601368  0.84669098]
 [0.17258836 0.76796194 0.56847019 0.67007494]
 [0.40706421 0.07845788 0.93546928 0.77494093]]
транспонована [[0.29619515 0.9800448  0.17258836 0.40706421]
 [0.55347917 0.29694267 0.76796194 0.07845788]
 [0.21943692 0.7601368  0.56847019 0.93546928]
 [0.73050168 0.84669098 0.67007494 0.77494093]]


10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [10]:
rng = np.random.default_rng()
m = rng.integers(low=1, high=11, size=(4))
n = rng.integers(low=1, high=11, size=(3, 4))
mn = n.dot(m)
print(m)
print(n)
print(f'перемножені матриця на вектор {mn}')

[5 7 4 3]
[[4 7 7 7]
 [3 3 7 9]
 [8 6 8 2]]
перемножені матриця на вектор [118  91 120]


11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [11]:
rng = np.random.default_rng()
o = rng.random(size=(3))
p = rng.random(size=(2, 3))
op = p.dot(o)
print(o)
print(p)
print(f'перемножені матриця на вектор {op}')

[0.11357927 0.17073407 0.02525836]
[[0.89000695 0.42124839 0.95823226]
 [0.51207796 0.11120361 0.39580839]]
перемножені матриця на вектор [0.19721117 0.08714516]


12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [12]:
rng = np.random.default_rng()
r = rng.integers(low=1, high=11, size=(2, 2))
s = rng.integers(low=1, high=11, size=(2, 2))
sr = s*r
print(s)
print(r)
print(f'поелементне множення {sr}')

[[6 5]
 [7 4]]
[[6 1]
 [8 9]]
поелементне множення [[36  5]
 [56 36]]


13 Cтворіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [13]:
rng = np.random.default_rng()
t = rng.integers(low=1, high=11, size=(2, 2))
u = rng.integers(low=1, high=11, size=(2, 2))
tu = t.dot(u)
print(t)
print(u)
print(f'добуток {tu}')

[[5 3]
 [3 4]]
[[4 3]
 [2 4]]
добуток [[26 27]
 [20 25]]


14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [14]:
rng = np.random.default_rng()
v = rng.integers(low=1, high=101, size=(5, 5))
print(v)
print(f'сума елементів матриці {v.sum()}')

[[67 34 28  3 10]
 [28 71 16 85 96]
 [14  6 51 53 31]
 [54 11 67 24 42]
 [69 39 29 72 68]]
сума елементів матриці 1068


15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [15]:
rng = np.random.default_rng()
w = rng.integers(low=1, high=11, size=(4, 4))
q = rng.integers(low=1, high=11, size=(4, 4))
print(w)
print(q)
print(f'різниця матриць {w-q}')

[[ 8 10  3  7]
 [ 4  2  9  6]
 [ 6  9  6  2]
 [ 6  7  6  8]]
[[4 7 3 7]
 [4 2 4 8]
 [3 7 7 7]
 [9 7 7 7]]
різниця матриць [[ 4  3  0  0]
 [ 0  0  5 -2]
 [ 3  2 -1 -5]
 [-3  0 -1  1]]


16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [16]:
rng = np.random.default_rng()
x = rng.random(size=(3, 3))
print(x)
vec_sum = np.array(x.sum(axis=1))
revec_sum = vec_sum.reshape((3, 1))
print(f' вектор суми елементів рядків {revec_sum}')

[[0.20851571 0.48374867 0.10575431]
 [0.41991875 0.08555456 0.76586907]
 [0.78722307 0.74208493 0.46052226]]
 вектор суми елементів рядків [[0.7980187 ]
 [1.27134238]
 [1.98983026]]


17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [17]:
rng = np.random.default_rng()
y = rng.integers(10, size=(3, 4))
print(y)
y2 = y**2
print(f'матриця з квадратами елементів  {y2}')

[[0 9 4 8]
 [9 5 4 0]
 [3 7 3 7]]
матриця з квадратами елементів  [[ 0 81 16 64]
 [81 25 16  0]
 [ 9 49  9 49]]


18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [18]:
rng = np.random.default_rng()
z = rng.integers(low=1, high=51, size=(4))
print(z)
z2 = np.sqrt(z)
print(f'вектор з коренями елементів  {z2}')

[35  3  8 17]
вектор з коренями елементів  [5.91607978 1.73205081 2.82842712 4.12310563]
